import { Images } from "../app/exports";
import { PropertyCardProps } from "../components/common/propertiesCard/PropertiesCard";

export const propertyData: PropertyCardProps[] = [
  {
    image: Images.singleFamilyThree,
    title: "Apartment/Condo",
    price: 350000,
    daysAgo: 10,
    address: "1056 Nicola Street Vancouver BC West End VWV",
    sqft: 1200,
    beds: 2,
    baths: 2,
    priceDrop: 10,
    assessedDiff: 1,
    realtor: "Jane Smith / Smith Realty Group",
    mls: "R3059142",
  },
  {
    image: Images.singleFamilyThree,
    title: "Luxury Condo",
    price: 489000,
    daysAgo: 5,
    address: "Davie Street Vancouver BC",
    sqft: 980,
    beds: 2,
    baths: 1,
    priceDrop: 5,
    assessedDiff: -2,
    realtor: "John Doe / Westview Realty",
    mls: "R2078332",
  },
  {
    image: Images.singleFamilyThree,
    title: "Luxury Condo",
    price: 489000,
    daysAgo: 5,
    address: "Davie Street Vancouver BC",
    sqft: 980,
    beds: 2,
    baths: 1,
    priceDrop: 5,
    assessedDiff: -2,
    realtor: "John Doe / Westview Realty",
    mls: "R2078332",
  },
  {
    image: Images.singleFamilyThree,
    title: "Luxury Condo",
    price: 489000,
    daysAgo: 5,
    address: "Davie Street Vancouver BC",
    sqft: 980,
    beds: 2,
    baths: 1,
    priceDrop: 5,
    assessedDiff: -2,
    realtor: "John Doe / Westview Realty",
    mls: "R2078332",
  },
  {
    image: Images.singleFamilyThree,
    title: "Luxury Condo",
    price: 489000,
    daysAgo: 5,
    address: "Davie Street Vancouver BC",
    sqft: 980,
    beds: 2,
    baths: 1,
    priceDrop: 5,
    assessedDiff: -2,
    realtor: "John Doe / Westview Realty",
    mls: "R2078332",
  },
  {
    image: Images.singleFamilyThree,
    title: "Luxury Condo",
    price: 489000,
    daysAgo: 5,
    address: "Davie Street Vancouver BC",
    sqft: 980,
    beds: 2,
    baths: 1,
    priceDrop: 5,
    assessedDiff: -2,
    realtor: "John Doe / Westview Realty",
    mls: "R2078332",
  },
];
export const dummyListings = [
  {
    id: 1,
    address: "90 Highland Dr #W/Sea, Orangeville, Ontario, Canada",
    beds: 2,
    baths: 5,
  },
  {
    id: 2,
    address: "2185 11th Concession W/Se, Trent Hills, Ontario, Canada",
    beds: 2,
    baths: 1,
  },
  {
    id: 3,
    address: "32 Weston Rd, Toronto, Ontario, Canada",
    beds: 3,
    baths: 2,
  },
  {
    id: 4,
    address: "32 Weston Rd, Toronto, Canada",
    beds: 3,
    baths: 2,
  },
  {
    id: 6,
    address: "90 Highland Dr #W/Sea, , Ontario, Canada",
    beds: 5,
    baths: 4,
  },
  {
    id: 7,
    address: "90 12th Concession W/Se, Ontario, Canada",
    beds: 5,
    baths: 4,
  },
  {
    id: 8,
    address: "9045 Weston Rd, Concession W/Se, BC, Canada",
    beds: 5,
    baths: 4,
  },
  {
    id: 9,
    address: "113 13TH AVE S CRANBROOK V1C 2V6",
    beds: 5,
    baths: 4,
  },
];
