const Icons = {
  bcClub: "../BCRealEstateMarket.svg",
  closeMenu: "../close-rounded.svg",
  openMenu: "../menu-motion.svg",
  heroMapVector: "../heroMapVector.svg",
  searchLine: "../search-line.svg",
  facebook: "../facebook.svg",
  instagram: "../instagram.svg",
  twitter: "../twitter.svg",
  emailIcon: "../emailIcon.svg",
  notFound: "../not_found.svg",
  bgWaveLine: "../bgWaveLine.svg",
  bathtub: "../bathtub.svg",
  bedroom: "../bedroom.svg",
  scale: "../scale.svg",
  lot: "../lotSize.svg",
  google: "../google.svg",
  courtorder: "../courtorder.svg",
  openhouse: "../openhouse.svg",
  soldicon: "../soldicon.svg",
  star: "../star.svg",
  save: "../save.svg",
  accurate: "../accurate.svg",
  free: "../free.svg",
  instantResult: "../instantResult.svg",
  arrowup: "../arrowup.svg",
  facebookicon: "../facebookicon.svg",
  twittericon: "../twittericon.svg",
  linkedin: "../linkedin.svg",
  print: "../print.svg",
  riveticons: "../riveticons.svg",
  compare: "../compare.svg",
  favorite: "../favorite.svg",
  property: "../property.svg",
  vectorMap: "../vectorMap.svg",
  garage: "../garage.svg",
  calendar: "../calendar.svg",
  grahp: "../grahp.svg",
  upArrow: "../upArrow.svg",
  downArrow: "../downArrow.svg",
  lotSize: "../lotSizeN.svg",
  bed: "../bedroomN.svg",
  bath: "../bathtubN.svg",
  square: "../scaleN.svg",
};

const Images = {
  apartment: "/apartment.webp",
  condoTwo: "/condoTwo.webp",
  townHouse: "/townHouse.webp",
  singleFamily: "/singleFamily.webp",
  singleFamilyTwo: "/singleFamilyTwo.webp",
  singleFamilyThree: "/singleFamilyThree.webp",
  map: "/map.webp",
  blogimg: "/blogimg.webp",
  firsttown: "/firsttown.webp",
  secondtown: "/secondtown.webp",
  leadership: "/leadership.webp",
  billwalsh: "/billwalsh.webp",
  saleimg: "/saleimg.webp",
  leaderlesson: "/leaderlesson.webp",
  assessment: "/assessment.webp",
  employee: "/employee.webp",
  mlsr: "/mlsr-logo.png",
  forSale: "/forSale.webp",
  sold: "/sold.webp",
  expired: "/expired.webp",
  mapImage: "/Map.png",
  foreCloser: "/forecloser.png",
};

export { Icons, Images };
